### ISSUE TITLE
Tune the thermosphere Eddy mixing parameters in WAM for a better TEC simulation by WAM-IPE 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM#12]
The TEC prediction by WAM-IPE are much lower compared with GloTEC. 
now we are doing an effort to tune the thermosphere Eddy mixing parameters in WAM to improve the WAM-IPE TEC simulation.
see issue #5 for the related background and former works.

**Comment by ZhuxiaoLi66** [comment]
two 20 days coupling runs (20130301-20130320) by ipe_fixes has been conducted. 
the eddy mixing coeffecient kamx has been set kmax=140 and kmax=180 in WAM, respectively. 
The output will be diagnosed soon.

**Comment by ZhuxiaoLi66** [comment]
The following plots are the 10 days average TEC comparison between kmax140 and kmax180 WAM-IPE self-consistent electric runs.The Fig3 is (TEC180-TEC140)/TEC140*100. TPavg is the global mean of change percentage , TPavg0 is the global mean of decrease area (except TP>0 area).
![Capture](https://user-images.githubusercontent.com/22546571/76665235-aa75fb00-654c-11ea-8bbd-4a5c7d868887.PNG)
![Capture1](https://user-images.githubusercontent.com/22546571/76665247-b792ea00-654c-11ea-81ad-d01467e8f42f.PNG)
![Capture5](https://user-images.githubusercontent.com/22546571/76665253-bb267100-654c-11ea-95f7-0ac726461af3.PNG)

**Comment by ZhuxiaoLi66** [comment]
diff of kmax180-kmax140, 

![TEC_diff_kmax180-140](https://user-images.githubusercontent.com/22546571/76804916-1c478200-67a3-11ea-83b2-6992b4879879.png)

**Comment by ZhuxiaoLi66** [comment]
The following is the TEC comparison between selfconsistent electric with Heelis and with new weimer. 

![TEC_kmax140_electric_heelis](https://user-images.githubusercontent.com/22546571/76900832-b5d46980-685f-11ea-9fb7-5c22d4597e2a.png)
![TEC_kmax140_electric_weimer2005](https://user-images.githubusercontent.com/22546571/76900860-c4228580-685f-11ea-92d1-7a6962d2e596.png)

**Comment by ZhuxiaoLi66** [comment]
It looks that the TEC of selfconsistent with new weimer is smaller compared with that with Heelis.

**Comment by ZhuxiaoLi66** [comment]
for another comparison with above plots, the following plot is the TEC by weimer_ipe_fixes with Heelis turns on. 
![TEC_kmax140_weimer_ipefixes_heelis_20130306-10](https://user-images.githubusercontent.com/22546571/77352203-75179d00-6d04-11ea-9e62-f80dfc6816c3.png)

**Comment by ZhuxiaoLi66** [comment]
The kmax=180 run by weimer_ipefixes with weimer self-electric run has been conducted. It seems that The time average TEC during quite time is not very different from the heelis self-electric in ipefixes branch. it is a reference for the comparison between GloTEC and WAM-IPE. 
  
![TEC_kmax180_weimer_ipefixes_20130306-15](https://user-images.githubusercontent.com/22546571/77352996-cbd1a680-6d05-11ea-9eed-01117eebe8cd.png)
![TEC_kmax180_ipefixes_heelis_20130306-15](https://user-images.githubusercontent.com/22546571/77353025-da1fc280-6d05-11ea-9fa1-6ca60ee08020.png)

**Comment by ZhuxiaoLi66** [comment]
@twfang it seems the heelis performance (at kt=140 case) in weimer_ipe_fixes branch in the above run is different from your runs, which has a smaller TEC than turn on the weimer in that branch. Is the smaller TEC with Heelis scheme the expected case after George's transport update? @gmillward @timfullerrowell

**Comment by ZhuxiaoLi66** [comment]
@twfang if convenient, could you also send me the reminder for Phil's meeting every week? would like to be an auditory to get some basic idea on IPE code and physics.  Thanks in ahead.

**Comment by ZhuxiaoLi66** [comment]
several WAM runs has been done for preparation the IC files (2013030100) for coupling simulation with larger values of keddy0_tracer, which are 220, 280 and 340, aiming to get compariable TEC by GloTEC.

**Comment by ZhuxiaoLi66** [comment]
![TEC_kmax340_develop_20130306-15](https://user-images.githubusercontent.com/22546571/79788994-c23c5e00-8306-11ea-82c7-59e2b28693ea.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_comparison_WAM-IPE_GlobTEC_20130316-17](https://user-images.githubusercontent.com/22546571/80406143-d50fdf00-8880-11ea-8e6c-89b1399294ba.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_WAM-IPE_kmax280_develop_weimer_20130306-15](https://user-images.githubusercontent.com/22546571/80406611-929ad200-8881-11ea-9c46-dc8bb9d50ef4.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_WAM-IPE_kmax220_develop_weimer_20130306-15](https://user-images.githubusercontent.com/22546571/80407054-3be1c800-8882-11ea-95a2-b666453907f7.png)

**Comment by ZhuxiaoLi66** [comment]
Based on the brief comparison, it seems that the magnitude of TEC (20130306-15) from WAM-IPE with keddy=220 is close to that from GloTEC (20130316).  The TEC performance of WAM-IPE during storm period (20130316-18) will be investigated.  Aiming for the further analysis,  Would like to get the digital output of GloTEC for 2013 and 2015 St. Patrick storm runs.

**Comment by ZhuxiaoLi66** [comment]
The following is the decrease amount of TEC with the increase of keddy coeffecient in WAM-IPE. 
 
![TEC_diff_WAM-IPE_kmax280-220_develop_weimer_20130306-15](https://user-images.githubusercontent.com/22546571/80408981-52d5e980-8885-11ea-956a-e332c421290d.png)
![TEC_diff_WAM-IPE_kmax340-280_develop_weimer_20130306-15](https://user-images.githubusercontent.com/22546571/80409016-62edc900-8885-11ea-886a-73968ccf42a2.png)
![TEC_diff_kmax180-140](https://user-images.githubusercontent.com/22546571/80409058-74cf6c00-8885-11ea-95ab-d83e12337ea6.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots are the TEC comparison of the 5 'develop_weimer' runs (keddy0=140, 180, 220, 280, 340) at specific UT. 

![TEC_0UT_kmax140-340_develop_weimer_20130306-15_5p](https://user-images.githubusercontent.com/22546571/80835222-909d7f80-8baf-11ea-85f2-51f118acccfd.png)
![TEC_6UT_kmax140-340_develop_weimer_20130306-15_5p](https://user-images.githubusercontent.com/22546571/80835259-a01cc880-8baf-11ea-99b1-0b25895ecda3.png)
 
The corresponding observational GPS TEC based on CEDAR MIT website is shown as following, 
![TEC_MIT_20130306-15_0UT_2deg](https://user-images.githubusercontent.com/22546571/103586743-f65eab80-4ea2-11eb-876f-2b43617558d3.png)
![TEC_MIT_20130306-15_6UT_2deg](https://user-images.githubusercontent.com/22546571/103586760-ff4f7d00-4ea2-11eb-9851-6615e0409e7e.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_12UT_kmax140-340_develop_weimer_20130306-15_5p](https://user-images.githubusercontent.com/22546571/80835344-cd697680-8baf-11ea-9ad2-6a67a7a1ef18.png)


![TEC_18UT_kmax140-340_develop_weimer_20130306-15_5p](https://user-images.githubusercontent.com/22546571/80835364-d6f2de80-8baf-11ea-8123-a6308100d4b4.png)

The corresponding mean GPS TEC based on the CEDAR MIT website is shown as following, 

![TEC_MIT_20130306-15_12UT_2deg](https://user-images.githubusercontent.com/22546571/103586912-59e8d900-4ea3-11eb-8c09-1535005b1d70.png)
![TEC_MIT_20130306-15_18UT_2deg](https://user-images.githubusercontent.com/22546571/103586927-5ead8d00-4ea3-11eb-9329-9a4466712437.png)

**Comment by ZhuxiaoLi66** [comment]
Tim made the following two plots which can indicate the TEC comparison between WAM-IPE and GloTEC during the quite time more clearly.

![TEC_0UT_WAM-IPE_GloTEC_20130316](https://user-images.githubusercontent.com/22546571/80995913-40672d00-8dfc-11ea-8c17-7dc46398afc9.png)
![TEC_18UT_WAM-IPE_GloTEC_20130316](https://user-images.githubusercontent.com/22546571/80995937-478e3b00-8dfc-11ea-9777-6d0abe2fce6c.png)

**Comment by ZhuxiaoLi66** [comment]
3 more runs with keddy0=100, 260, 300 has been conducted. The following is the TEC comparison at specific UT for the total 7 runs. 

![TEC_0UT_keddy100_340_7p](https://user-images.githubusercontent.com/22546571/81449634-ec32b480-913d-11ea-8ff3-f2a3f5551f50.png)


![TEC_12UT_keddy100_340_7p](https://user-images.githubusercontent.com/22546571/81449669-fd7bc100-913d-11ea-895c-c2e0dc503503.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_12UT_keddy100_340_7p](https://user-images.githubusercontent.com/22546571/81449704-11bfbe00-913e-11ea-8111-e1695bc4e908.png)

![TEC_18UT_keddy100_340_7p](https://user-images.githubusercontent.com/22546571/81449726-184e3580-913e-11ea-95fc-fc718e10ba8f.png)

**Comment by ZhuxiaoLi66** [comment]
several WAM standalone (20130301-15) and MSIS runs has been conducted to do the global mean vertical profile comparison on neutral density and some O/N2 analysis.
also conducted some storm WAM runs (20130316-19 with 180s cedence output) with different skeddy0 to check the influence of the skeddy0 change on the total number density (DEN), especially during the storm time, will compare them with the former satellite storm (2013 St. Patrick) validation.

**Comment by ZhuxiaoLi66** [comment]
The global mean neutral number density (O, O2, and N2) during 20130306-0315 from runs with different skeddy0 values (current base line is 140 in WAM) has been comparied with the corresponding MSIS output. The Kp and F107 values in the MSIS run is the time mean of the input Kp and F107 for WAM during the period of 20130306-0315. 
The following plots shows the results, and the baseline one (skeddy0=140) is the closest one to MSIS, maybe since we orginally tuned the skeddy0 by static MSIS results. The encourage thing is that it seems if we move to skeddy0=180 or 220 for better TEC sake, the neutral number density will not change largely. more aspects about neutral density will be investigated later.

**Comment by ZhuxiaoLi66** [comment]
![global_number_density_20130306-15_msis_kmax100](https://user-images.githubusercontent.com/22546571/83315787-8a66e700-a1df-11ea-85cb-e54568e246e5.png)
![global_number_density_20130306-15_msis_kmax140](https://user-images.githubusercontent.com/22546571/83315793-905cc800-a1df-11ea-872b-ac5faff77cb1.png)
![global_number_density_20130306-15_msis_kmax180](https://user-images.githubusercontent.com/22546571/83315801-9ce12080-a1df-11ea-9464-4a2a16cd6d0d.png)

**Comment by ZhuxiaoLi66** [comment]
![global_number_density_20130306-15_msis_kmax220](https://user-images.githubusercontent.com/22546571/83315824-bd10df80-a1df-11ea-8d64-6fe5fc0e1a6c.png)
![global_number_density_20130306-15_msis_kmax300](https://user-images.githubusercontent.com/22546571/83315830-c13cfd00-a1df-11ea-8085-420398c2548e.png)
![global_number_density_20130306-15_msis_kmax340](https://user-images.githubusercontent.com/22546571/83315834-c4d08400-a1df-11ea-86ea-6a17e783a5cd.png)

**Comment by ZhuxiaoLi66** [comment]
please notice that the MSIS results in the above plots are not change, since the time mean of Kp and F107 during 20130306-15 is the same.

**Comment by timfullerrowell** [comment]
Excellent. Thanks Zhuxiao.
A very clear trend.

The departures at the top are probably Helium so nothing to worry about.
At the same p and T it puts a little too much of the total number density
(n = p/kT )into the O, O2, and N2 that should start to go into Helium.
Tim

**Comment by ZhuxiaoLi66** [comment]
Thanks, Tim.

**Comment by ZhuxiaoLi66** [comment]
The total number density output (every 3 mins) for several storm runs (20130316-0319) with different skeddy0 has been interpolated into fixed height and validated agaist GOCE satellite data alone its orbits (point-to-point).
The results shown in the following plots. 
![GOCE_validation_20130317_skeddy0_100_ori](https://user-images.githubusercontent.com/22546571/84064288-9a20c100-a97f-11ea-8c7d-a5bd416021e6.png)
![GOCE_validation_20130317_skeddy0_180_ori](https://user-images.githubusercontent.com/22546571/84064365-b7558f80-a97f-11ea-8bd4-11aab8fae58a.png)
![GOCE_validation_20130317_skeddy0_220_ori](https://user-images.githubusercontent.com/22546571/84064629-2cc16000-a980-11ea-8bb4-d1d157ac19e9.png)
![GOCE_validation_20130317_skeddy0_300_ori](https://user-images.githubusercontent.com/22546571/84064653-38ad2200-a980-11ea-9288-a9c08a793e4e.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots shows the corresponding global mean Temperature of the above runs. 
![Temp_global_skeddy0_100_MSIS_20130306-0315_norm](https://user-images.githubusercontent.com/22546571/84390294-932ec400-abb4-11ea-9d25-11cfc7744545.png)
![Temp_global_skeddy0_140_MSIS_20130306-0315_norm](https://user-images.githubusercontent.com/22546571/84390333-a477d080-abb4-11ea-828e-c2c1c6886a03.png)
![Temp_global_skeddy0_180_MSIS_20130306-0315_norm](https://user-images.githubusercontent.com/22546571/84390356-af326580-abb4-11ea-89a0-47a4fdbfd378.png)
![Temp_global_skeddy0_260_MSIS_20130306-0315_norm](https://user-images.githubusercontent.com/22546571/84390380-bb1e2780-abb4-11ea-84ab-4d0fdc9ea615.png)
![Temp_global_skeddy0_340_MSIS_20130306-0315_norm](https://user-images.githubusercontent.com/22546571/84390406-c4a78f80-abb4-11ea-8cbd-2b6ebd209248.png)

**Comment by ZhuxiaoLi66** [comment]
Tim, the temperature change kind of larger in the runs with skeddy0's value above 180. 
so in fomular 0. P=nkT, the number density should decrease at same pressure level. 
As for the two mechnism 1. rho=mn     2. H=RT/mg that compete for rho value at fixed height, 
the results indicates the m (Mean Mass)  in the first mechism dominant the rho (mass density) value. 
since n should smaller due to T increase? The increse T looks also contribute to the secondary for mechinism 2. now I understand that the air less expanding can make the rho value smaller at a given height at ralative high altitude (not troposhere or somewhere below 60km).  
I will check our former Temp. validation results for eddy mixing experiments. Unfortunately, I can't open the plots in my google drive these two days, I tried to delete some data file with large size, while not succeed, will google more or ask some one else.

**Comment by ZhuxiaoLi66** [comment]
the composition dependent absorption of solar EUV is a good explaination for the increase of temperature in case of keddy0 value becoming larger, even we don't change the teddy0 in another scheme. 
The time mean O/N2 for each runs are calculating for the quantitative estimate.

**Comment by ZhuxiaoLi66** [comment]
The brief comparison between TEC from WAM-IPE and the CEDAR MIT TEC, the absence of data over the ocean for the latter is significant. 
https://user-images.githubusercontent.com/22546571/80835222-909d7f80-8baf-11ea-85f2-51f118acccfd.png
![TEC_MIT_2013031600_LOG10_NCL](https://user-images.githubusercontent.com/22546571/102538520-9b872080-4069-11eb-82ae-319c916d1499.png)

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,
Can you plot the MIT data on a linear scale with the same range?
Tim

**Comment by ZhuxiaoLi66** [comment]
Hi Tim, 
the following plot is on a linear scale with the same range, seems that the magnitude of maximum TEC belt over South America is consistent with WAM TEC with keddy0=140 & 180 cases, maybe more consistent with keddy0=180 case. 
![TEC_MIT_2013031600_NCL_cb](https://user-images.githubusercontent.com/22546571/102550799-afd41900-407b-11eb-8eea-0a5eb6d912f2.png)

**Comment by ZhuxiaoLi66** [comment]
https://github.com/NOAA-SWPC/WAM/issues/12#issuecomment-622529296

**Comment by ZhuxiaoLi66** [comment]
https://github.com/NOAA-SWPC/WAM/issues/12#issuecomment-622529631

**Comment by ZhuxiaoLi66** [comment]
Tim, please have a look at the following TEC comparison (WAM.vs. MIT GPS). just please double click the links, it will go to the place of the plots, Thanks.   

https://github.com/NOAA-SWPC/WAM/issues/12#issuecomment-622529296
https://github.com/NOAA-SWPC/WAM/issues/12#issuecomment-622529631

**Comment by ZhuxiaoLi66** [comment]
![TEC_20130306-15_0UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105756652-1e718580-5f0a-11eb-9d0e-0bb5284377de.png)
![TEC_20130306-15_06UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105756661-229da300-5f0a-11eb-8ae0-389fa8506cf3.png)
![TEC_20130306-15_12UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105756673-25989380-5f0a-11eb-8b28-2589612bbca2.png)
![TEC_20130306-15_18UT_MIT_grid](https://user-images.githubusercontent.com/22546571/105756684-28938400-5f0a-11eb-952f-6207c2c69b10.png)

**Comment by ZhuxiaoLi66** [comment]
![image](https://user-images.githubusercontent.com/22546571/105756821-5d9fd680-5f0a-11eb-855f-a16c4015fefc.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_MIT_interpolated_20130306](https://user-images.githubusercontent.com/22546571/105768726-086bc100-5f1a-11eb-8613-4a257230c335.png)

**Comment by twfang** [comment]
We will redo all the comparisons with operational outputs with GloTEC. Thus, the issue is closed for now.
