### ISSUE TITLE
Update WAM Namelist

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM#13]
This is a fairly low priority issue, but as the first step in part of a larger effort to update some of the physics schemes to bring NEMS-WAM closer in line with NEMS-GSM, we must first update the namelist options to use more the more modern Monin Hybrid EDMF (moninedmf) scheme in place of the older moninq, as well as some further suggestions from Fanglin Yang of EMC:
```
dspheat=.true.
cnvcld=.true.
cal_pre=.true.

cdmbgwd=3.0, 0.25 
psautco=0.0002,0.0002
prautco=0.0001,0.0001
```
dspheat is kinetic dissipative heating, used in moninq (but more relevantly in moninedmf), cnvcld has to do with convective clouds, and cal_pre is a new precipitation type algorithm. cdmbgwd is a combined parameter for the multiplicative components of mountain blocking and gravity wave drag. This is a resolution-dependent parameter, and may require additional tuning. psautco/prautco are auto conversion coefficients for the conversion of ice to snow and cloud to rain respectively.

Fanglin also suggested `redrag=.true.` while Valery has told me it should be off -- as far as I can tell, it just reduces the surface drag coefficient for wind over water. The only reference in the model physics is phys/sfc_diff.f:

```
      real(kind=kind_phys), parameter ::
     &              z0s_max=.317e-2       ! a limiting value at high winds over sea
[...]
          if (redrag) then
            z0(i) = min(z0(i),z0s_max)
          else
            z0(i) = min(z0(i),.1)
          endif
```

Based on this, I'm inclined to follow Fanglin's advice, although as cdmbgwd there may be a resolution-dependent component to this chosen z0s_max that isn't necessarily valid at T62, although it's worth noting that this is a prescribed value and not one that can be altered via the namelist.

Introducing these new default namelist parameters is trivial, but the conditions for acceptance into development will require some verification work.

**Comment by akubaryk** [comment]
new_namelist branch has been created (in GSMWAM-IPE) -- should do some standalone WAM test runs to inspect the impact.

**Comment by ZhuxiaoLi66** [comment]
will do a test run with these new options later.

**Comment by ZhuxiaoLi66** [comment]
The validation work of the new_namelist branch against the wam-ipe_scripts_v2 branch is going on. Since the namelist variable options change is related to the physics scheme & parameter change, the output based on longer period (3 mons) from these two branch are ready for comparison. plan to do the 2013 St. Patrick storm case comparison.

**Comment by ZhuxiaoLi66** [comment]
Hi Adam, about the value setting of cdmbgwd, what is Valery's suggestion again? cdmbgwd=0.125, 0.125?  the current one is cdmbgwd=3.0, 0.25.

**Comment by akubaryk** [comment]
0.125, 3.0 (or 3.5 can't remember and don't have my notes with me anymore).

**Comment by akubaryk** [comment]
Found it

```
!========
! C96:   cdmbgwd=      "0.125,     3.0"
!C192:   cdmbgwd=      "0.2,       2.5"
!C384:   cdmbgwd=      "1.0,       1.2"
!C768:   cdmbgwd=      "3.5,       0.25"
!========   
```

**Comment by ZhuxiaoLi66** [comment]
Thanks, Adam. Could you please point me out the FFLAGS setting for WAM in old repository? seems not found the proper makefile.  Thanks.

**Comment by ZhuxiaoLi66** [comment]
The new_namelist branch has been verified against v2_scripts branch. 
The neutral Temp. and wind at about 250km and zonal mean Temp. at all levels has been tested by two 3 month runs , we can say that at quite time, the new namelist changed the Temp. at vert mild way with near 0 avg.
![diff_T_250km_namelist_v2_20130315](https://user-images.githubusercontent.com/22546571/72845459-958c9200-3c96-11ea-8266-dab6c3266201.png)
![diff_T_LAT_H_namelist_v2_20130301_15](https://user-images.githubusercontent.com/22546571/72845474-99b8af80-3c96-11ea-99d9-71f524bbcd46.png)

**Comment by akubaryk** [comment]
Great work. Is it easy to plot that last set of panels as the lowest 45 layers with a significantly reduced scale (-5 to 5 or maybe even less)? Curious what the features look like in the troposphere, as that'll affect the data assimilation somewhat.

**Comment by ZhuxiaoLi66** [comment]
While during storm time, the difference of Temp. at 250km enlarged with the base temp. increase. 
it seems a numerical responding other than physics, it is happened when we includes v2_scripts. 
 
![diff_T_250km_namelist-v2_20130317](https://user-images.githubusercontent.com/22546571/72846118-d20cbd80-3c97-11ea-8c82-864f66d49799.png)
![diff_T_250km_namelist_v2_20130318](https://user-images.githubusercontent.com/22546571/72846126-d76a0800-3c97-11ea-8b76-10d7bad34378.png)

**Comment by ZhuxiaoLi66** [comment]
@akubaryk will do.

**Comment by ZhuxiaoLi66** [comment]
![45levs](https://user-images.githubusercontent.com/22546571/72849381-742fa400-3c9e-11ea-9a0d-5406fcd2323f.png)

**Comment by ZhuxiaoLi66** [comment]
Aiming to confirm that the temperature change during storm time by the change in some physics parameters in new_namelist branch is within a 'reasonable' range, two runs by ori_v2_script branch with very slight difference (5tsp away) in init files has been compared, its magnitude of the Temp. difference is similar with the one with the new parameter values in new_namelist. 

![T_diff_250km_5tsp_20130317](https://user-images.githubusercontent.com/22546571/73208760-e987f280-413e-11ea-8730-44fbc21aeb92.png)
![T_diff_250km_5tsp_20130318](https://user-images.githubusercontent.com/22546571/73208779-edb41000-413e-11ea-8724-7c4b98196a09.png)

**Comment by ZhuxiaoLi66** [comment]
The number density at about 250km by new_namelist branch with Satellite validation has also been conducted, it is similar with the validation results by the WAM version before this branch. 
![num_den_Grace_validation_20150317](https://user-images.githubusercontent.com/22546571/73209141-8d719e00-413f-11ea-8c93-60cce6e9e9da.png)
![Grace_den_WAM_original](https://user-images.githubusercontent.com/22546571/73209214-b2fea780-413f-11ea-8ffe-62557113d56d.png)

**Comment by ZhuxiaoLi66** [comment]
Here is the WAM num den with Grace validation for the 4 days' data (20150316-0319).
![num_den_namelist_GRACE_validation_20150316_4days](https://user-images.githubusercontent.com/22546571/73490882-556b9480-43a5-11ea-89d1-852bb2eb0949.png)

**Comment by ZhuxiaoLi66** [comment]
The following is Martin's explanation on the spikes of GRACE data in the old validation plots. Sounds reasonable.
The older plots had a different IDL smoothing function parameter that was not consistent with each orbit. For example, it took 70 data points for a full orbit, and the older plot overaged over 62. Now, the averaging is every 70 points. This adjustment smoothed the averaging which removed the spikes in the orbit-averaged values.

**Comment by twfang** [comment]
Here is the comparison of the WAM-IPE coupled run on 2013/03/18 with self-consistent electrodynamics. 

<img width="969" alt="Screen Shot 2020-02-01 at 3 57 45 PM" src="https://user-images.githubusercontent.com/22968399/73600315-a2697b00-450b-11ea-8e73-d36159702223.png">
