### ISSUE TITLE
Upgrade WAM mesh

### ISSUE THREAD

**Issue by rmontuoro** [SWPC-IPE/WAM#17]
WAM exported fields used in WAM-IPE coupling are built on a simplified mesh, which can only represent WAM's original reduced Gaussian grid in index space. Spatial coordinates and connectivity are unavailable in such mesh, preventing further regridding of WAM's exported fields by a coupled component (_e.g._ SWIO).

The current mesh needs to be completed to include spatial coordinates and connectivity information.

**Comment by rmontuoro** [comment]
WAM's mesh was updated to include spatial coordinates and connectivity to fully describe the GSM reduced Gaussian grid. A plot of the updated mesh is included below:

![image](https://user-images.githubusercontent.com/18299064/75926180-b61c4000-5e2f-11ea-917a-bf5e075fc6cc.png)

**Comment by ZhuxiaoLi66** [comment]
@rmontuoro So it is a combining of the octahedral mesh and the original mesh?

![image](https://user-images.githubusercontent.com/22546571/75931530-74d95f80-5e32-11ea-804f-8ded69e71779.png)

**Comment by ZhuxiaoLi66** [comment]
@rmontuoro the other GFS with GSM also use the mesh you showed above? thanks.

**Comment by twfang** [comment]
Some results from the new SWIO from WAM. I think it looks reasonable. 

![swio_wam_neutral](https://user-images.githubusercontent.com/22968399/75947285-12e21f80-5e5d-11ea-987a-d7d2b6eb5979.png)

**Comment by rmontuoro** [comment]
> @rmontuoro So it is a combining of the octahedral mesh and the original mesh?
> 
@ZhuxiaoLi66, the plot shows a mesh representation of the reduced Gaussian grid (based on NCEP's T62 grid) used by GFS and WAM GSMs. Such grid is built as an ESMF Mesh object since ESMF does not have the ability to represent a reduced Gaussian grid as a Grid object.

**Comment by ZhuxiaoLi66** [comment]
@rmontuoro got it, thanks.
@twfang could you please run 20130316-20130317 with the new SWIO? thanks.

**Comment by twfang** [comment]
@rmontuoro 
Is this issue completed? If yes, please close it. Thanks!

**Comment by rmontuoro** [comment]
PR #18 addressed this issue.
