### ISSUE TITLE
testing the new repository GSMWAM-IPE

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM#2]
The new repository GSMWAM-IPE has the new features of NEMS which has been updated in UFS. 
the wam-ipe_scripts branch in NOAA-SWPC/GSMWAM-IPE has been used to do the validation on this repository against the original WAM version before adapt the new NEMS and to test the new developments in this repository.

**Comment by ZhuxiaoLi66** [comment]
plan to do some more comparison between origin 'merge' branch and the wam-ipe_scripts_v2 branch. Already got 3 days (20130316-18) and 3 mons (20130101-0330) output.

**Comment by twfang** [comment]
Zhuxiao, are we able to close this issue?
