### ISSUE TITLE
WAM mass density including Helium extrapolation to 1000km 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM#28]
This work is aiming to make the WAM mass density data at fixed heights extrapolated to 1000km and including Helium density for the CRADA with a Texas group to check if WAM structure helps the satellite orbit propagation.   
A structured code set has been established to make the WAM mass density data. 
The dataset is for the case of Mar.16-19 2015 St. Patrics storm at first. 
The Helium mixing ratio at WAM 140 pressure level is gotten from calling the MSIS2.0. By this mechanism, we include the Helium component to calculate the new WAM mass density.    
The code set for this work is expected to build up the structure for routinely producing the WAM mass density data at fixed heights to 1000km.

**Comment by ZhuxiaoLi66** [comment]
The dataset has been created, the validation work is on. 
The following are plots for the data at different height levels and compared with the original method without extrapolation and helium including. more validation will take.

**Comment by ZhuxiaoLi66** [comment]
![DEN_fixed_height_100km_1000km_helium_250km](https://user-images.githubusercontent.com/22546571/116012282-e9e39780-a5e6-11eb-8b68-6e113515a5d6.png)
![DEN_fixed_height_old_250km](https://user-images.githubusercontent.com/22546571/116012287-f23bd280-a5e6-11eb-80ff-382ba134c412.png)
![DEN_fixed_height_100km_1000km_helium_400km](https://user-images.githubusercontent.com/22546571/116012289-f5cf5980-a5e6-11eb-9321-6ee700e6b995.png)
![DEN_fixed_height_old_400km](https://user-images.githubusercontent.com/22546571/116012291-f962e080-a5e6-11eb-9d28-6a254c6bff66.png)
![DEN_fixed_height_100km_1000km_helium_500km](https://user-images.githubusercontent.com/22546571/116012296-fcf66780-a5e6-11eb-8460-339beb7309dd.png)
![DEN_fixed_height_100km_1000km_helium_800km](https://user-images.githubusercontent.com/22546571/116012300-0089ee80-a5e7-11eb-9e0e-7bfa2f13b4ac.png)

**Comment by timfullerrowell** [comment]
Thanks Zhuxiao,

Are all the "new fixed height den" with or without Helium?
Is this mainly a test of the new fixed height grid from gsm output and
extrapolation, or are some with Helium.

Tim

**Comment by ZhuxiaoLi66** [comment]
Hi Tim, 
all the 'new fixed height den' includes the Helium by our algorithm. At low height levels (250km even 400km) it should be very close to our former interpolation results (ori_opr) as the above plots show. 
While my current concern is that at high height levels (500km), the 'new fixed height DEN' after we include Helium is still very close to the former results. I also made a code to extrapolate (to 1000km) the same output without including Helium (call MSIS), its DEN is very close (too close) to the DEN with Helium at 500km and 800km levels. will do further thinking & code checking later, maybe need to discuss it with you tomorrow or after.
Zhuxiao

**Comment by ZhuxiaoLi66** [comment]
The above problem has been solved by finding a bug in the code, now the values of the number density of Helium look reasonable and the total mass density at high levels (800km) has increased significantly with the algorithm of inclusion of the Helium. the following are the 6 hourly plots for number density and mass density profiles for 20150316 and 20150317 two days and the comparison with the first order of number & mass density profiles Tim sent to me. The basic results are consistent and it is very nice to see the change of the number densities and mass densities at the storm time (20150317).
It is a success resulting from making the storm mode input to MSIS2.0 and the calling to it. 
the results need further thinking and discuss though.  

![num_density_new_fixed_height_He_5profiles_20150316](https://user-images.githubusercontent.com/22546571/116471959-8188f600-a832-11eb-9936-3ab5912b45e6.png)
![num_mass_densities_first_order_profiles](https://user-images.githubusercontent.com/22546571/116471883-6b7b3580-a832-11eb-8dea-ed64b40731bf.png)
![num_density_new_fixed_height_He_5profiles_20150317](https://user-images.githubusercontent.com/22546571/116471910-72a24380-a832-11eb-8e05-85fd31ac63f7.png)

![mass_density_new_fixed_height_He_5profiles_20150317](https://user-images.githubusercontent.com/22546571/116472038-9796b680-a832-11eb-8375-35c5bc7d58b9.png)
![num_mass_densities_first_order_profiles](https://user-images.githubusercontent.com/22546571/116472046-9a91a700-a832-11eb-9500-a83202c8ae45.png)
![mass_density_new_fixed_height_He_5profiles_20150316](https://user-images.githubusercontent.com/22546571/116472055-9e252e00-a832-11eb-8cd2-3a571dfb3f40.png)

**Comment by timfullerrowell** [comment]
Excellent. Thanks Zhuxiao.

It is possible to extrapolate the Helium down, as well as up, if we want to
pretty the plot, but it makes virtually no practical difference to the
total density.

I would be interested to see the difference if you use the MSIS without the
storm mode input for the Helium. My expectation is that it should not make
a lot of difference to the profile.
Tim

**Comment by ZhuxiaoLi66** [comment]
Tim, you are right, the profiles of number and mass density of Helium are much more pretty after I made the downward extrapolation on Helium.  And the whole profile plots looks more close to the historical profiles you sent. the following are the new number & mass density profile plots for 20150317 (0316 one is similiar). 
  
![num_density_new_fixed_height_He_5profiles_20150317](https://user-images.githubusercontent.com/22546571/116740363-2aaa2a80-a9b2-11eb-8725-8077ec11ead9.png)
![num_mass_densities_first_order_profiles](https://user-images.githubusercontent.com/22546571/116740395-33026580-a9b2-11eb-84cf-eeac246f505b.png)
![mass_density_new_fixed_height_He_5profiles_20150317](https://user-images.githubusercontent.com/22546571/116740408-3990dd00-a9b2-11eb-93ea-50a6df0bf0b4.png)

**Comment by ZhuxiaoLi66** [comment]
The kind of dissapointed thing is that as you said, the storm mode of MSIS2.0 doesn't offer a quite different mixing ratio of Helium, so it doesn't change the total mass density much. we get the almost same total mass density at the storm time at 500km and 800km.

**Comment by timfullerrowell** [comment]
Perfect. Thanks Zhuxiao.

On the MSIS storm response, that's exactly what I was hoping for and
expecting.
I wanted the storm Helium response to be driven by the WAM parameters and
not dependent on the MSIS storm forcing.
So far from a disappointment, it is exactly what it should have done, and
what we need.

Tim

**Comment by ZhuxiaoLi66** [comment]
Got it, thanks, Tim!

**Comment by ZhuxiaoLi66** [comment]
A bug has been found and fixed in the downward extrapolation code which affected the total density about 400km height. 
The new output now looks fine and is downloading from Hera and will be uploaded the google drive later. 
The following are the new checking plots. 
![DEN_output_debug_400km_20150317](https://user-images.githubusercontent.com/22546571/118538172-1765c180-b70b-11eb-9c2e-e4aa2d2e41c6.png)
![DEN_output_debug_400km_20150316](https://user-images.githubusercontent.com/22546571/118538176-17fe5800-b70b-11eb-9387-cce3b1b8d0e7.png)
![DEN_output_debug_400km_20150319](https://user-images.githubusercontent.com/22546571/118538223-23ea1a00-b70b-11eb-811c-f56c45fd6ac0.png)
![DEN_output_debug_400km_20150318](https://user-images.githubusercontent.com/22546571/118538226-2482b080-b70b-11eb-869a-6ede3dfcf2ad.png)

**Comment by twfang** [comment]
Thanks @ZhuxiaoLi66 
Could you please send me the path of these outputs on Hera?

**Comment by ZhuxiaoLi66** [comment]
@twfang, the output is Hera:/scratch1/NCEPDEV/swpc/Zhuxiao.Li/save/MSIS2.0/data/
zz_WAM_den_helium_2015031600-031800_final_output_debug.nc
zz_WAM_den_helium_2015031800-032000_final_output_debug.nc

**Comment by ZhuxiaoLi66** [comment]
The new WAM DEN dataset has been verified by Tim and me.  it looks good at all checked aspects. The following plots are the comparison of the global total mass density with & without the helium including. The helium including has significant 
effect on the magnitude of total mass density, especially during quiet time. 
 
![DEN_output_profiles_helium_nohelium_20150316_2](https://user-images.githubusercontent.com/22546571/119390422-4390bd80-bc8a-11eb-9f25-998dcc70c62c.png)
![DEN_output_profiles_helium_nohelium_20150317_2](https://user-images.githubusercontent.com/22546571/119390451-4d1a2580-bc8a-11eb-99b4-74f1afcfddbf.png)
![DEN_output_profiles_helium_nohelium_20150318_2](https://user-images.githubusercontent.com/22546571/119390464-50adac80-bc8a-11eb-86ad-22810e584308.png)
![DEN_output_profiles_helium_nohelium_20150319_2](https://user-images.githubusercontent.com/22546571/119390475-54d9ca00-bc8a-11eb-9e6b-e74ed6082f91.png)

**Comment by ZhuxiaoLi66** [comment]
![DEN_output_profiles_helium_nohelium_20210626](https://user-images.githubusercontent.com/22546571/125340462-baa01500-e30f-11eb-8a4f-c85260730184.png)

**Comment by ZhuxiaoLi66** [comment]
![wfs_fixed-height_den_400km_20210626](https://user-images.githubusercontent.com/22546571/125340533-cdb2e500-e30f-11eb-9723-e5568c5fec40.png)
![wfs_fixed-height_den_400km_20150316](https://user-images.githubusercontent.com/22546571/125340672-fe931a00-e30f-11eb-9416-50b1bce8e867.png)

**Comment by ZhuxiaoLi66** [comment]
![wfs_fixed-height_den_800km_20210626](https://user-images.githubusercontent.com/22546571/125340703-0783eb80-e310-11eb-8fe3-00b78a890c25.png)
![wfs_fixed-height_den_800km_20150316](https://user-images.githubusercontent.com/22546571/125340716-0bb00900-e310-11eb-919f-1d50d94fa168.png)

**Comment by ZhuxiaoLi66** [comment]
![MSIS_fixed-height_den_400km_20210626](https://user-images.githubusercontent.com/22546571/125834955-2f14bf42-6e3a-4d93-ad50-ee64715ce809.png)
![MSIS_fixed-height_den_800km_20210626](https://user-images.githubusercontent.com/22546571/125834960-b48a65ce-d6fa-4aed-9813-f628bc1c5e96.png)

**Comment by twfang** [comment]
Using the outputs from the operational version, we are able to provide neutral density above the model top after all the validations. Thus, this issue is closed.
