### ISSUE TITLE
solar heating calculated incorrectly due to type error in idea_solar_heating

### ISSUE THREAD

**Issue by akubaryk** [SWPC-IPE/WAM#36]
@SvetlanaKarol-NOAA noted this issue via email. There's an incorrect type error in [idea_solar_heating.f](https://github.com/NOAA-SWPC/WAM/blob/421547ea7ce97e53c0ba404b17e32f2eef5a97b0/src/phys/idea_solar_heating.f#L259) that leads to `dayno` being interpreted as effectively 0 in the subroutine `solar_heat_dissociation_TIEGCM`. As a result, `sfeps` is always a little over 1.03363, while the value should vary like this according to day of year:

![image](https://user-images.githubusercontent.com/31134616/178579045-03d1630a-c69e-45fe-b868-1c19340461d4.png)

a difference of almost 6.5% in the NH summer.

A branch `bugfix/solar_heating` will be pushed shortly -- we should identify the impact on the model.

**Comment by ZhuxiaoLi66** [comment]
Will take a look tomorrow. Thanks,
Zhuxiao

**Comment by ZhuxiaoLi66** [comment]
The influence of the 'dayno' bugfix on total number density & TEC has been checked with two WAM-IPE free runs for June 2015 with real-time drivers. 
The ratios (bugfix/ori) of the monthly mean of total number density at 400km and TEC  had been described in the following plots.

**Comment by ZhuxiaoLi66** [comment]
![den_400km_ratio_dayno_bugfix_201506_4p_cb](https://user-images.githubusercontent.com/22546571/185997252-39cb5188-2ed9-49e0-93f1-dcbacd213666.png)
![den_400km_ratio_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/185997292-46804860-52f4-450c-b0e3-71eae83a71b6.png)
![TEC_ratio_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/185997319-97a38dfd-637e-472c-be9b-d1d279ed28f5.png)

**Comment by ZhuxiaoLi66** [comment]
![TEC_after_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/185997729-d8449608-247e-4d48-9c91-30008e01a027.png)
![TEC_ori_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/185997733-dabbba01-661d-46e5-9c04-f35810267bba.png)

**Comment by ZhuxiaoLi66** [comment]
The following plots are the monthly mean (June 2015) total number density at 400km by the dayno_fix code and the original code respectively. 
![den_400km_before_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/186014245-5ddc83f5-caf4-4963-80e1-22007099aa6c.png)
![den_400km_dayno_bugfix_201506_4p](https://user-images.githubusercontent.com/22546571/186014247-494acb91-3178-4245-af23-913a45bb0b59.png)
