### ISSUE TITLE
WAM Validation: Check WAM's MMS for low plasma density from cycling run compared with GloTec 

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM#5]
Dom and Houjun did the comparison of TEC between Houjun's 'nowi' version cycling run and the GloTec output. The results shows that 'nowi' has consistent low TEC compared with GloTec. The works in this issue will help to figure out what is the cause for that.

**Comment by akubaryk** [comment]
checked sigf03 between the two WCOSS runs and they were bitwise identical, new tar file here: /scratch4/NCEPDEV/stmp4/Adam.Kubaryk/opsdat/sigf2.tar

**Comment by akubaryk** [comment]
There is no difference, they are bitwise identical through the prior failure point before the F10.7=68 issue was addressed.

**Comment by akubaryk** [comment]
There's the similar run on Theia in /scratch4/NCEPDEV/stmp3/Adam.Kubaryk/houjpara for comparison if you need something there -- 11 day from the 2019051500 initial conditions with realtime input parameters on a 3hr cycle.
